# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Milestone Project 13-15' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Milestone Project 13-15
pod 'SkeletonView'
pod 'SVGKit'

end
